#!/usr/bin/env python3
# Generate projects/<project>/BUILD.bazel for every museum project, wiring its
# upstream build/test targets to the //runner/image container via runner_project.
#
#   python3 runner/gen_targets.py
#
# Reads each builds/<project>/BUILD.bazel: the @<key>_archive source key, the
# known-good bazel_version, and the build_spec/test_spec target lists (which are
# already upstream labels, e.g. //:cpuinfo). The museum overlay machinery is
# ignored — the runner path builds the project exactly as upstream ships it.
import re
import pathlib

# A few museum build targets reference an external repo because the museum
# consumes the project as a dependency; the runner builds the project's own root
# target instead.
BUILD_OVERRIDE = {
    "doctest": ["//:doctest"],
}


def labels(text, kind):
    m = re.search(kind + r"\s*\(\s*targets\s*=\s*\[(.*?)\]", text, re.S)
    return re.findall(r'"([^"]+)"', m.group(1)) if m else []


def fmt(targets):
    inner = ", ".join('"%s"' % t for t in targets)
    return "[%s]" % inner


def main():
    root = pathlib.Path(__file__).resolve().parent.parent
    count = 0
    for build_file in sorted((root / "builds").glob("*/BUILD.bazel")):
        text = build_file.read_text()
        if "museum_project(" not in text:
            continue
        proj = build_file.parent.name
        km = re.search(r'source_archive = "@([a-z0-9_]+)_archive//file"', text)
        if not km:
            continue
        key = km.group(1)
        vm = re.search(r'bazel_version = "([^"]+)"', text)
        version = vm.group(1) if vm else "9.1.1"
        build = BUILD_OVERRIDE.get(proj, labels(text, "build_spec"))
        test = labels(text, "test_spec")

        lines = [
            "# GENERATED by runner/gen_targets.py — do not edit by hand.",
            '# "%s" built/tested as upstream ships it, inside //runner/image.' % proj,
            'load("//projects:defs.bzl", "runner_project")',
            "",
            "runner_project(",
            '    name = "%s",' % key,
            '    version = "%s",' % version,
        ]
        if build:
            lines.append("    build = %s," % fmt(build))
        if test:
            lines.append("    test = %s," % fmt(test))
        lines.append(")")
        out = build_file.parent.parent.parent / "projects" / proj / "BUILD.bazel"
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text("\n".join(lines) + "\n")
        count += 1
        print("wrote projects/%s/BUILD.bazel  (key=%s bazel=%s build=%d test=%d)"
              % (proj, key, version, len(build), len(test)))
    print("== %d project packages ==" % count)


if __name__ == "__main__":
    main()
